CREATE TABLE incarceration_data (
	key VARCHAR(255) PRIMARY KEY,
	year DATE,
	state VARCHAR(255),
	county VARCHAR(255),
	facility_name VARCHAR(255),
	confined_population INT,
	adult_male INT,
	pct_white DECIMAL(4,4),
	black_population INT,
	pct_black DECIMAL(4,4),
	hispanic_population INT,
	pct_hispanic DECIMAL(4,4),
	native_american_population INT,
	pct_native_american DECIMAL(4,4),
	asian_population INT,
	pct_asian DECIMAL(4,4),
	native_hawaiian_pacific_islander_population INT,
	pct_native_hawaiian_pacific_islander DECIMAL(4,4),
	two_or_more_races_population INT,
	pct_two_or_more_races DECIMAL(4,4),
	other_population INT,
	pct_other DECIMAL(4,4)	
);