CREATE TABLE state_data (
	key VARCHAR(255) PRIMARY KEY,
	state VARCHAR(255),
	year DATE,
	confined_population INT,
	adult_male INT,
	pct_adult_male DECIMAL(4,4),
	adult_female INT,
	pct_adult_female DECIMAL(4,4),
	juvenile_male INT,
	pct_juvenile_male DECIMAL(4,4),
	juvenile_female INT,
	pct_juvenile_female DECIMAL(4,4),
	white_population INT,
	pct_white DECIMAL(4,4),
	black_population INT,
	pct_black DECIMAL(4,4),
	hispanic_population INT,
	pct_hispanic DECIMAL(4,4),
	native_american_population INT,
	pct_native_american DECIMAL(4,4),
	asian_population INT,
	pct_asian DECIMAL(4,4),
	native_hawaiian_pacific_islander_population INT,
	pct_native_hawaiian_pacific_islander DECIMAL(4,4),
	two_or_more_race_population INT,
	pct_two_or_more_race DECIMAL(4,4),
	other_population INT,
	pct_other DECIMAL(4,4)	
);